import { useEffect, useRef, useState, type ReactNode } from 'react';
import { MotionConfig, motion, useReducedMotion } from 'motion/react';
import { Download, Linkedin, Github, Menu, X, Mail, Code2, Database, Server, Layers, ChevronDown, GraduationCap, Cpu } from 'lucide-react';
import { navigation, profile } from './data/profile';
import { experience } from './data/experience';
import { projects, type Project } from './data/projects';
import { skills } from './data/skills';

function Reveal({children,className=''}:{children:ReactNode;className?:string}) {
 const reduced=useReducedMotion();
 return <motion.div className={className} initial={reduced?false:{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.1}} transition={{duration:.45}}>{children}</motion.div>;
}
function Resume({compact=false}:{compact?:boolean}) {return <a className={`button ${compact?'small':'secondary'}`} href={profile.resume} download><Download size={16}/>{compact?'Resume':'Download resume'}{!compact&&<span className="format">DOCX</span>}</a>}
function Socials(){return <div className="socials"><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17}/>LinkedIn</a>{profile.github?<a href={profile.github} target="_blank" rel="noreferrer"><Github size={17}/>GitHub</a>:<span className="pending"><Github size={17}/>GitHub <small>link pending</small></span>}</div>}
function SectionTitle({number,title,caption}:{number:string;title:string;caption?:string}){return <div className="section-title"><div><span className="eyebrow">{number} / {title.toUpperCase()}</span><h2>{title}</h2></div>{caption&&<p>{caption}</p>}</div>}
function Architecture(){return <div className="architecture" aria-label="Project architecture: React frontend, FastAPI backend, PostgreSQL and Redis, in Docker Compose"><div className="visual-label"><span>APPLICATION ARCHITECTURE</span><span>01</span></div><div className="architecture-flow"><div className="node"><Code2/><span>React<small>Frontend</small></span></div><div className="connector"/><div className="node core"><Server/><span>FastAPI<small>API layer</small></span></div><div className="connector"/><div className="data-pair"><div className="node"><Database/><span>PostgreSQL</span></div><div className="node"><Layers/><span>Redis</span></div></div></div><div className="container-label">Docker Compose <span>·</span> One local environment</div></div>}
function ProjectCard({project,index}:{project:Project;index:number}){return <Reveal className={`project-card project-${project.id}`}><div className="project-visual">{project.id==='task'?<Architecture/>:project.id==='math'?<div className="project-concept"><Code2 size={30}/><div className="formula">f(x) = learning</div><div className="visual-foot">50+ practice questions <span>Flutter / Dart</span></div></div>:<div className="project-concept sensor"><Cpu size={30}/><div className="sensor-labels"><span>Pressure</span><span>Temperature</span><span>Humidity</span></div><div className="visual-foot">Environmental sensing <span>Arduino / C++</span></div></div>}</div><div className="project-content"><span className="eyebrow">0{index+1} / {project.kind}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.stack.map(t=><span key={t}>{t}</span>)}</div><details><summary>Engineering notes <ChevronDown size={16}/></summary><ul>{project.details.map(d=><li key={d}>{d}</li>)}</ul>{project.github&&<p><a href={project.github} target="_blank" rel="noreferrer">View source on GitHub</a></p>}{project.demo&&<p><a href={project.demo} target="_blank" rel="noreferrer">Open live demo</a></p>}{!project.github&&!project.demo&&<p className="link-note">Repository and live demo links have not been provided.</p>}</details></div></Reveal>}
export default function App(){
 const [menu,setMenu]=useState(false);const [active,setActive]=useState('home');const menuRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id)})},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!menu)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);menuRef.current?.focus()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[menu]);
 return <MotionConfig reducedMotion="user"><a className="skip-link" href="#main">Skip to content</a><header><div className="nav-shell"><a href="#home" className="brand" aria-label="Jaysal Manchanda home">jm<span>.</span></a><nav aria-label="Main navigation" className={menu?'open':''} id="navigation">{navigation.map(item=><a key={item} href={`#${item.toLowerCase()}`} aria-current={active===item.toLowerCase()?'location':undefined} onClick={()=>setMenu(false)}>{item}</a>)}</nav><div className="nav-actions"><Resume compact/><button ref={menuRef} className="menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main id="main"><section id="home" className="hero wrapper"><Reveal><div className="hero-meta"><span className="eyebrow">JAYSAL MANCHANDA</span><span className="eyebrow subtle">COMPUTER SCIENCE · UC SAN DIEGO</span></div><h1>Thoughtful software.<br/><span>From interface</span><br/><span>to infrastructure.</span></h1><div className="hero-bottom"><div><p className="hero-intro">I’m Jaysal, a Computer Science student at UC San Diego. I build full-stack applications and explore the systems that keep them running.</p><div className="hero-actions"><a href="#projects" className="button primary">View projects</a><Resume/></div><Socials/></div><div className="hero-index" aria-hidden="true"><span>01 — INTERFACES</span><span>02 — BACKEND SYSTEMS</span><span>03 — CLOUD & INFRASTRUCTURE</span><div className="index-rule"/><span className="index-bottom">BUILD WITH INTENT.</span></div></div></Reveal><div className="hero-footer"><span>SOFTWARE ENGINEERING PORTFOLIO</span><a href="#about">A little more about me <ChevronDown size={14}/></a><span>2026</span></div></section>
 <section id="about" className="wrapper section"><Reveal><SectionTitle number="01" title="Curious by default."/><div className="about-grid"><div className="about-copy"><p className="large-copy">I like understanding how the <em>whole thing</em> works.</p><p>From a React interface to an API and the infrastructure underneath it, I’m drawn to the connections between each layer. Building practical software gives me a way to turn that curiosity into something useful.</p><p>I’m studying Computer Science at UC San Diego, with experience in frontend development and an interest in backend engineering, cloud infrastructure, and DevOps.</p></div><aside className="education"><GraduationCap size={26}/><span className="eyebrow">CURRENTLY STUDYING</span><h3>University of California,<br/>San Diego</h3><p>B.S. Computer Science</p><div className="education-foot"><span>2024 — 2028</span><span>Marshall College</span></div></aside></div></Reveal></section>
 <section id="experience" className="wrapper section"><Reveal><SectionTitle number="02" title="Learning by building." caption="Internships and research, from user interfaces to real-world data."/><div className="timeline">{experience.map((job,i)=><article className="job" key={job.company}><div className="job-side"><span className="job-number">0{i+1}</span><div><h3>{job.company}</h3><p>{job.dates}</p></div></div><div className="job-body"><h4>{job.role}</h4><p className="job-team">{job.team}</p>{job.note&&<p className="content-note">{job.note}</p>}<ul>{job.points.map(p=><li key={p}>{p}</li>)}</ul><div className="tags">{job.technologies.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></Reveal></section>
 <section id="projects" className="wrapper section"><SectionTitle number="03" title="Selected work." caption="A closer look at what I’ve built—and what happens beneath the surface."/><div className="projects-grid">{projects.map((p,i)=><ProjectCard key={p.id} project={p} index={i}/>)}</div></section>
 <section id="skills" className="wrapper section"><Reveal><SectionTitle number="04" title="My toolkit." caption="Tools I’ve used across coursework, projects, and internships."/><div className="skills-grid">{skills.map((s,i)=><div className="skill" key={s.name}><span className="eyebrow">0{i+1}</span><h3>{s.name}</h3><p>{s.items.join(' · ')}</p></div>)}</div></Reveal></section>
 <section id="contact" className="wrapper section contact"><Reveal><span className="eyebrow">05 / LET’S CONNECT</span><h2>Good software starts<br/>with a <em>conversation.</em></h2><p>Have an engineering opportunity or a project in mind?<br/>I’d love to hear about it.</p><a className="email" href={`mailto:${profile.email}`}><Mail size={23}/>{profile.email}</a><Socials/></Reveal></section></main>
 <footer className="wrapper footer"><a className="brand" href="#home">jm<span>.</span></a><span>© {new Date().getFullYear()} Jaysal Manchanda</span><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href={`mailto:${profile.email}`}>Email</a><a href="#home">Back to top</a></footer></MotionConfig>
}
